
# Data config
GROUPED_COLS: ['item','store','date']
LABEL_COL: sales
INDEX_COL: date

# Model Parameters
# LSTM
LSTM_PARAMS:
  - LSTM_WINDOW_LENGTH: 29
  - LSTM_PREDICTION_LAG: 90
  - LSTM_NODES: 30
  - LSTM_EPOCHS: 10
  - LSTM_BATCH: 256
  - LSTM_LR: 0.003

# XGBoost
XGB_PARAMS:
  - XGB_MAX_DEPTH: 3
  - XGB_ETA: 0.2
  - XGB_SILENT: 1
  - XGB_SUBSAMPLE: 1
  - XGB_NUM_ROUNDS: 1000